= Qorvo's QSPICE Examples from https://www.microwavejournal.com/blogs/32-rf-signal-integrity-to-power-integrity[RF Signal Integrity to Power Integrity] series blog/article

== Overview
This repository offers examples used in a series blog/articles on https://www.microwavejournal.com/[Microwave Journal (MWJ)] written by a Qorvo engineer https://www.microwavejournal.com/authors/5278-masashi-nogawa-sr-member-of-technical-staff-qorvo[Masashi Nogawa].

The contents are mixture of following kind of files.

* QSPICE simulation decks / schematics (**.qsch**)
* Netlist files (**.cir**) for QSPICE from the **.qsch** schematics (above).
* Python scripts (**.py**) as post data processor, plotting simulation results


== About QSPICE
Qorvo offers a free simulation tool QSPICE, that is a very fast running SPICE.
On this QSPICE platform, Qorvo keeps offering simulation models of power management ICs and power SiC transistor devices (products of, formerly known as, UnitedSiC).

QSPICE is available from https://www.MarcusAureliusSoftware.com/InstallQSPICE.exe[this URL] for free.


== Licenses of examples in this repository
NOTE: Please kindly let us know when you find other licenses to be mentioned here.

* The QSPICE files of file-extensions ".qsch", ".cir" and ".qraw" are under the https://github.com/MasashiNogawa/DPT-on-MSO6/blob/main/LICENSE[license of Qorvo].

* The Python script codes of file-extension ".py", writtne by Qorvo, are also under the https://github.com/MasashiNogawa/DPT-on-MSO6/blob/main/LICENSE[license of Qorvo].


== Dependencies / Libraries to be Installed on Your PC

* The Python script "qspice.py", that is handling QSPICE output file, is a sub-class of https://pypi.org/project/ltspice/["ltspice" library] and this "ltspice" lib is needed to install ">> pip install ltspice".
We are working to add our own methods, as sub-class, handling QSPICE specific data formats.
* The parent "ltspice" lib requires commonly used Python libraries.
** https://pypi.org/project/matplotlib/[matplotlib]
** https://pypi.org/project/numpy/[numpy]

..end of README


